# yaml-language-server: $schema=<https://uniform.app/schemas/json-schema/component-definition/v1.json>
$schema: https://uniform.app/schemas/json-schema/component-definition/v1.json
id: listItem
name: List Item
icon: screen
parameters:
  - id: title
    name: Title
    type: text
    typeConfig: null
    localizable: true
  - id: subtitle
    name: Subtitle
    type: text
    typeConfig:
      multiline: true
    localizable: true
  - id: icon
    name: Icon
    type: asset
    typeConfig:
      max: 1
  - id: link
    name: Link
    type: link
    typeConfig:
      linkTypes:
        tel: false
        email: false
useTeamPermissions: true
slots: []
titleParameter: title
thumbnailParameter: icon
canBeComposition: false
created: '2024-08-23T18:04:30.693931+00:00'
updated: '2024-08-23T18:04:30.693931+00:00'
