id: listItem
name: List Item
created: '2024-08-23T18:30:35.849685+00:00'
updated: '2024-08-23T18:30:35.849685+00:00'
slugSettings: {}
useTeamPermissions: true
fields:
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig: null
    localizable: true
  - id: subTitle
    name: Sub Title
    type: text
    helpText: ''
    typeConfig:
      multiline: true
    localizable: true
entryName: title
icon: file-document
type: block
permissions: []
